name: Build Android TV APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.3'
      - name: Build TV Release APK
        run: |
          cd simple_live_tv_app
          flutter pub get
          flutter build apk --release
      - name: Upload TV APK
        uses: actions/upload-artifact@v4
        with:
          name: Simple-Live-TV-APK
          path: simple_live_tv_app/build/app/outputs/flutter-apk/app-release.apk

